services:
  app:
    build: .
    container_name: laravel-formation-app
    restart: unless-stopped
    ports:
      - "8000:80"
    working_dir: /app
    volumes:
      - ./laravel-app:/app
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000

      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite

      REDIS_HOST: redis
      REDIS_PORT: 6379

      CACHE_STORE: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    depends_on:
      - redis
    command: >
      sh -c "
        touch /app/database/database.sqlite &&
        php artisan key:generate --force || true &&
        php artisan migrate --force || true &&
        frankenphp php-server -r public/
      "

  redis:
    image: redis:latest
    container_name: laravel-formation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  laravel_storage:
  redis_data:
